tasks:
- name: spring-petclinic
  before: cd spring-petclinic
  init: make build
  command: make run
- name: typescript-node-example
  before: cd typescript-node-example
  init: make build
  command: make run
  openMode: split-right
